name: QueueRestartStandalone
version: '${project.version}'
main: me.diffusehyperion.queuerestartstandalone.QueueRestartStandalone
api-version: 1.19
softdepend:
  - DiscordSRV
commands:
  queuerestart:
    usage: /queuerestart (duration) (reason)
    aliases: queuereboot
  queuestop:
    usage: /queuestop (duration) (reason)
    aliases: queueshutdown
  queuecancel:
    usage: /queuecancel
